spring:
  application:
    name: CAR-MANAGEMENT
  datasource:
    url: jdbc:postgresql://dpg-csrh8368ii6s73b66qh0-a.oregon-postgres.render.com:5432/carmgmt?sslmode=require
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
